id: P13CCE411
initial_creation_type: input
source_metadata:
  id: ''
  title: bonpokangyur
  language: bo
  author: ''
  sutra:
    Bon1:
      repeat: ''
      vol: ༼ཀ༽ (༡) ༼ཁ༽ (༢)
      page: ༼ཀ༽ 1-1-1a1~1-1-283b, ༼ཁ༽ 2-1-1a1~2-1-293b2
      tname: འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད།
      wylie: '''dus pa rin po che''i rgyud/'
      aname: འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད་གཟེར་མིག
      sname: ''
      yname: ཨ་དཀར་ཧ་ཏྲག་མུ་ལ་རམ།
      roman: ''
      cname: ''
      cid: ''
      homage: འཁོར་བའི་སེམས་ཅན་ཐམས་ཅད་འདྲེན་པའི་དཔལ། །གཤེན་རབ་སྟོན་པའི་མཆོག་ལ་ཕྱག་འཚལ་ལོ།
        །
      subject: གཙོ་བོར་ཚེ་ལོ་བརྒྱ་པའི་སྟོན་པ་རྒྱལ་བ་གཤེན་རབ་མི་བོའི་རྣམ་ཐར་དང་། རྗོད་བྱེད་ཀྱི་ཚིག་ལ་ལེའུ་བཅོ་བརྒྱད།
      topic: 0
      yana: 0
      school: 0
      chakra: 0
      location: ''
      audience: ''
      author: གཤེན་རབ་ཉིད་ཀྱི་ཞལ་ནས་གསུངས།
      requester: ''
      dharma: ''
      purpose: ཚིག་བཞི་ཚིགས་སུ་བཅད་པ་གཅིག་གིས་རྟོགས་ན་རབ་མཆོག་རྒྱལ་བ་ཡིན། །རྟོགས་ནས་དོན་བཞིན་བྱས་ན་འབྲས་བུ་མྱུར་དུ་འཐོབ།
        །ཚོག་གི་ལོ་མ་མང་པོ་མ་རྟོགས་བསྟན་ཕྱིར་ཡིན། །རྟོགས་ནས་དོན་བཞིན་མི་སྒོམ་རང་ལ་སྒུ་བ་བྱེད་པ་སྟེ།
        །སེམས་ཀྱིས་ས་ལེར་ཤེས་བཞིན་མེ་དཔུང་ནང་དུ་མཆོངས་པ་ཡིན། །ཞེས་སྟོན་པས་ཕྱི་རྒྱུད་ལས་གསུངས་སོ།
        །
      collect: ''
      bampo: ''
      relation: ''
      debate: འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད་གཟེར་མིག་གི་ལེའུ་བཅོ་བརྒྱད་པ་འདི་ནི། སྟོན་པའི་ཞལ་ནས་གསུངས་པའི་བོན་སྒོ་བཞི་མཛོད་དང་ལྔའི་ནང་ནས།
        གཙང་མ་མཐོ་ཐོག་སྤྱི་རྒྱུག་ཏུ་གཏོགས་སོ། །གཙང་མ་མཐོ་ཐོག་སྤྱི་རྒྱུག་ནི། མདོ་ཆེན་པོ་བཞི་བཞུགས་སོ།
        །བཞི་བཞུགས་པ་གང་ཞེ་ན། དུས་གསུམ་གཤེན་རབ་བྱུང་ཁུངས་ཀྱི་མདོ་དང་གཅིག །ཁམས་གསུམ་སེམས་ཅན་སྐྱེ་འཆིའི་མདོ་དང་གཉིས།
        འཇིག་རྟེན་སྣོད་བཅུད་འབྱུང་བ་ཆགས་འཇིག་གི་མདོ་དང་གསུམ། བླ་མེད་གོ་འཕང་སྒྲུབ་ཐབས་ཀྱི་མདོ་དང་བཞིའོ།
        །འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད་འདི་ནི། མདོ་ཆེན་པོ་བཞིའི་ནང་ནས། དུས་གསུམ་གཤེན་རབ་བྱུང་ཁུངས་ཀྱི་མདོར་གཏོགས་སོ།
        །དེ་ལ་ཡང་སྔ་རབས་འདས་པ་དང༌། སླད་ཀྱིས་འབྱོན་པའི་རྣམས་ནི་ཟུར་ཙམ་སྒྲ་འཕངས་ནས་བསྟན་པའོ།
        །ད་ལྟའི་སྟོན་པ་གཤེན་རབ་ཇི་བཞིན་འབྱོན་ཅིང་། འདས་པའི་ལོ་རྒྱུས་ཞིབ་པར་འདིའི་ནང་ནས་བསྟན་པའོ།
        །འདས་པ་དང་མ་བྱོན་པ་གཉིས་ཀའི་གཏན་ཚིགས་ནི། དུས་གསུམ་གཤེན་རབ་བྱུང་ཁུངས་ཀྱི་མདོ་ཡི་ནང་ན་ཞིབ་པའོ།
        །འདུས་པ་རིན་པོ་ཆེ་འདི་མདོ་ཆེན་པོ་བཞིའི་ནང་ནས་བཏུས་ཅིང་གཞན་དུ་བཀོལ་པའོ། །
      translator: འདི་དང་པོ་གཤེན་རབ་ཉིད་ཀྱི་ཞལ་ནས་གསུངས། གཤེན་རབ་མྱ་ངན་ལས་འདས་ནས།
        གདུང་འཚོབ་མུ་ཆོ་ལྡེམ་དྲུག་གིས། གཤེན་རབ་ཀྱི་བཀའ་ལ་བརྟེན་ནས། རིག་པ་མང་པོར་ཕྱེས།
        མུ་ཆོ་འདས་ནས་མཁས་པ་རིམ་པས་བྱུང༌། རྟག་གཟིགས་ལ་མཁས་པ་དམུ་ཙ་ཏྲ་ཧེ་ཕེ་དང༌། ཁྲི་ཐོག་པར་ཙ་མ་དང༌།
        འགུར་ཧི་ལི་སྤར་ཡ་དང་གསུམ་བྱུང་།དེ་ནས་རྫུ་འཕྲུལ་གྱི་རྐང་པ་ཐོབ་པའི་ལོ་ཙྪ་བ་གསུམ་བྱུང་སྟེ།
        རྒྱ་གར་ལ་མཁས་པ་ལྷ་བདག་སྔགས་དྲོ་དང༌། རྒྱ་ནག་ལ་མཁས་པ་ལེགས་ཏང་རྨང་པོ་དང༌། ཁྲོམ་ལ་མཁས་པ་གསེར་ཐོགས་ལྕེ་འབྱམས་གསུམ་གྱིས་བསྒྱུར་ཅིང་གཏན་ལ་ཕབ་པའོ།
        །དེ་ནས་མཁས་པ་ཆེན་པ་བཞི་བྱུང་སྟེ། བོད་ལ་མཁས་པ་ལྡེ་གྱིམ་ཚ་རྨ་ཆུང་དང༌། མི་ཉག་ལ་མཁས་པ་ལྕེ་ཚ་མཁར་བུ་ཆུང་དང༌།
        སུམ་པ་ལ་མཁས་པ་མུ་སྤུངས་གསལ་ཏང་དང༌། ཞང་ཞུང་ལ་མཁས་པ་སྟོང་རྒྱུང་མཐུ་ཆེན་དང༌།
        བོད་ལ་མཁས་པ་སེ་ཤ་རི་དབུ་ཆེན་དང་།དེ་རྣམས་ལས་འགྱུར་བ་མང་གིན། མཁས་པ་དེ་བཞིའི་རིང་ལ་བོན་གྱི་བསྟན་པ་དར་བ་ལ།
        བར་དུ་ཆོས་ཀྱི་འཕྲ་དོགས་དེས་གོང་དུ་། སོང་བས། ཉོན་མོངས་པ་སྐྱེས་ནས་བསྣུབས་སོ།
        །དུས་སུ་བབ་པས་དྲང་རྗེ་བཙུན་པ་གསེར་མིག་གིས། ལྷོ་ཕུགས་ཀྱི་གླིང་ཁྲི་དང་དུར་ཁྲོད་ནང་ནས་སྒོད་ནས་འཕེལ་བའོ།
        །བཏོན་ནས་གཏན་ལ་ཕབས་སོ། །
      reviser: ''
      age: 0
  window.__data:
  - id: 447564
    text: གཟེར་མིག
    bo: གཟེར་མིག
    en: Texts of the Bön Tradition
    zh-TW: 苯教藏經
    zh-CN: 苯教藏经
    KdbId: 71
    SutraId: 58060
    pbStart: 2426118
    pbEnd: 2427289
    nodes:
    - id: 447565
      text: ཀ
      bo: གཟེར་མིག ༼ཀ༽
      en: Volume 1, ༼ཀ༽
      zh-TW: 第一函 ༼ཀ༽
      zh-CN: 第一函 ༼ཀ༽
      KdbId: 71
      SutraId: 58060
      pbStart: 2426118
      pbEnd: 2426682
      nodes:
      - id: 447566
        text: འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད།
        bo: None
        en: None
        zh-TW: None
        zh-CN: None
        KdbId: 71
        SutraId: 58060
        pbStart: 2426118
        pbEnd: 2426682
        nodes:
        - id: 447567
          text: གཅིག་པ། སྔ་རབས་འདས་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426119
          pbEnd: 2426132
        - id: 447568
          text: གཉིས་པ། གཤེན་རབ་ཀྱི་ཡབ་ཡུམ་གྱི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426132
          pbEnd: 2426154
        - id: 447569
          text: གསུམ་པ། གཤེན་རབ་སྐྱེ་བ་བཞེས་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426154
          pbEnd: 2426193
        - id: 447570
          text: བཞི་པ། གཤེན་རབ་ཀྱི་བསྟན་པ་སྤེལ་བའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426193
          pbEnd: 2426206
        - id: 447571
          text: ལྔ་པ། ལྷ་གཤེན་བརྒྱ་ལ་ཕྱག་བཙལ་བའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426206
          pbEnd: 2426266
        - id: 447572
          text: དྲུག་པ། ལྷ་མོ་སུམ་བརྒྱ་ལ་ཕྱག་བཙལ་བའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426266
          pbEnd: 2426337
        - id: 447573
          text: བདུན་པ། གཤེན་རབ་ཀྱི་ཁབ་བཞེས་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426337
          pbEnd: 2426352
        - id: 447574
          text: བརྒྱད་པ། གཤེན་རབ་ཀྱིས་སྲས་སྤྲུལ་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426352
          pbEnd: 2426415
        - id: 447575
          text: དགུ་པ། ལྷ་གཤེན་སྲིད་པ་གཤེན་རབ་སྟོང་ལ་ཕྱག་འཚལ་བའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426415
          pbEnd: 2426626
        - id: 447576
          text: བཅུ་པ། གཤེན་རབ་ལ་བདུད་ཀྱིས་ཆོ་འཕྲུལ་སྣ་དགུ་བསྟན་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426626
          pbEnd: 2426682
    - id: 447577
      text: ཁ
      bo: གཟེར་མིག ༼ཁ༽
      en: Volume 2, ༼ཁ༽
      zh-TW: 第二函 ༼ཁ༽
      zh-CN: 第二函 ༼ཁ༽
      KdbId: 71
      SutraId: 58060
      pbStart: 2426682
      pbEnd: 2427289
      nodes:
      - id: 447578
        text: འདུས་པ་རིན་པོ་ཆེའི་རྒྱུད།
        bo: None
        en: None
        zh-TW: None
        zh-CN: None
        KdbId: 71
        SutraId: 58060
        pbStart: 2426682
        pbEnd: 2427246
        nodes:
        - id: 447579
          text: བཅུ་གཅིག་པ། བདུད་ཀྱི་གཤེན་རབ་ཀྱི་འཁོར་ལ་ཆོ་འཕྲུལ་བསྟན་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426683
          pbEnd: 2426772
        - id: 447580
          text: བཅུ་གཉིས་པ། གཤེན་རབ་ཀྱི་ནོར་ལ་བདུད་ཀྱིས་ཆོ་འཕྲུལ་བསྟན་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426772
          pbEnd: 2426834
        - id: 447581
          text: བཅུ་གསུམ་པ། གཤེན་རབ་ཀྱི་བསྟན་པ་རྣམ་པ་གསུམ་རྗེས་སུ་བཞག་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426834
          pbEnd: 2426916
        - id: 447582
          text: བཅུ་བཞི་པ། གཤེན་རབ་ཀྱི་འཕྲིན་ལས་བཅོ་བརྒྱད་ཀྱི་དོན་བསྟན་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2426916
          pbEnd: 2427038
        - id: 447583
          text: བཅོ་ལྔ་པ། སྟོན་པའི་ཁྱིམ་སྤོངས་རབ་ཏུ་བྱུང་བའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2427038
          pbEnd: 2427108
        - id: 447584
          text: བཅུ་དྲུག་པ། སྟོན་པས་འཁོར་རྣམས་སྤངས་ནས་དགོན་པ་མཛད་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2427108
          pbEnd: 2427140
        - id: 447585
          text: བཅུ་བདུན་པ། སྟོན་པ་མི་རྟག་མྱ་ངན་ལས་འདས་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2427140
          pbEnd: 2427226
        - id: 447586
          text: བཅོ་བརྒྱད་པ། སླད་ཀྱི་སྟོན་པ་ཇི་ལྟར་འབྱོན་པའི་ལེའུ།
          bo: None
          en: None
          zh-TW: None
          zh-CN: None
          KdbId: 71
          SutraId: 58060
          pbStart: 2427226
          pbEnd: 2427246
      - id: 447587
        text: མདོ་གཟེར་མིག་གི་དཀར་ཆག་ང་བཞུགས།
        bo: None
        en: None
        zh-TW: None
        zh-CN: None
        KdbId: 71
        SutraId: 58061
        pbStart: 2427246
        pbEnd: 2427260
      - id: 447588
        text: མཛད་ཆེན་བཅུ་གཉིས་ཀྱི་རྣམ་བཤད་མདོར་བསྡུས་པ།
        bo: None
        en: None
        zh-TW: None
        zh-CN: None
        KdbId: 71
        SutraId: None
        pbStart: 2427260
        pbEnd: 2427289
created_at: '2022-01-09T12:34:45.241367'
last_modified_at: '2022-01-09T12:34:45.241376'
